import { EducationLevel, ImportanceLevel, PrimaryIntent, RelationshipMode, TriState } from '@/types/database'

export type FieldTargetTable = 'profiles' | 'intentions' | 'trait_profiles' | 'conversations'
export type FieldCategory = 'fact' | 'sensitive' | 'summary' | 'meta'
export type FieldValueType =
  | 'string'
  | 'number'
  | 'string_array'
  | 'education'
  | 'education_array'
  | 'primary_intent'
  | 'relationship_mode'
  | 'tri_state'
  | 'boolean'
  | 'date_time'
  | 'json'

export type FieldSpec = {
  key: string
  label: string
  targetTable: FieldTargetTable
  category: FieldCategory
  valueType: FieldValueType
  matchingRole: 'hard' | 'soft' | 'pending' | 'reference' | 'meta'
  autoApply: 'always' | 'when_high_confidence' | 'review_on_conflict'
  importanceEligible?: boolean
  options?: readonly string[]
  description: string
  extractRule: string
  updateRule: string
}

export const V1_FIELD_SPECS = [
  {
    key: 'talked_at',
    label: '谈话时间',
    targetTable: 'conversations',
    category: 'meta',
    valueType: 'date_time',
    matchingRole: 'meta',
    autoApply: 'review_on_conflict',
    description: '本次实际沟通发生时间，默认等于上传时间，只有证据明确时才修正。',
    extractRule: '只有转录稿里明确出现实际沟通时间时才输出。',
    updateRule: '明确的新时间可覆盖默认上传时间；模糊时间不要覆盖。',
  },
  {
    key: 'name',
    label: '姓名',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'review_on_conflict',
    description: '当前红娘用于识别客户的姓名或固定称呼。',
    extractRule: '只有客户身份明确且出现清晰称呼时才提取。',
    updateRule: '新明确称呼可覆盖旧值；身份冲突时进入 review。',
  },
  {
    key: 'phone',
    label: '联系方式',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'when_high_confidence',
    description: '红娘内部用于联系客户的手机号或微信。',
    extractRule: '只有客户明确提供联系方式时才提取。',
    updateRule: '新明确联系方式覆盖旧值。',
  },
  {
    key: 'nationality',
    label: '国籍',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户当前国籍。',
    extractRule: '只有客户明确说出国籍时才提取。',
    updateRule: '新明确国籍覆盖旧值。',
  },
  {
    key: 'languages',
    label: '语言',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string_array',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户长期使用或熟练使用的语言列表。',
    extractRule: '只提取客户明确说会说、常用的语言。',
    updateRule: '新增语言增量合并；明确否认时可移除。',
  },
  {
    key: 'age',
    label: '年龄',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户当前年龄，以周岁计。',
    extractRule: '只有明确说出年龄时才提取。',
    updateRule: '新的明确年龄覆盖旧年龄；模糊表达不能覆盖。',
  },
  {
    key: 'height',
    label: '身高',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户当前身高，统一按厘米记录。',
    extractRule: '只有客户明确说出身高数值时才提取，例如164、一米六四、164厘米。',
    updateRule: '新的明确身高覆盖旧值；模糊表达不能覆盖。',
  },
  {
    key: 'city',
    label: '所在城市',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户当前主要生活或工作城市。',
    extractRule: '只提取明确主城市，口语地名要归一化。',
    updateRule: '新明确常驻城市覆盖旧值。',
  },
  {
    key: 'current_base_cities',
    label: '常驻城市',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string_array',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户长期频繁停留或往返的城市列表。',
    extractRule: '只在客户明确说经常往返/常驻时提取。',
    updateRule: '新增城市增量合并。',
  },
  {
    key: 'residency_status',
    label: '居留状态',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '户籍、签证、长期居留等状态。',
    extractRule: '只提取明确说明的居留状态。',
    updateRule: '新明确状态覆盖旧值。',
  },
  {
    key: 'travel_frequency',
    label: '流动频率',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户跨城或国际出行频率。',
    extractRule: '只提取客户明确描述的长期流动节奏。',
    updateRule: '新明确描述覆盖旧值。',
  },
  {
    key: 'education',
    label: '学历',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'education',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    options: ['high_school', 'associate', 'bachelor', 'master', 'phd', 'other'],
    description: '客户当前最高正式学历。',
    extractRule: '只接受明确学历表达，统一到枚举值。',
    updateRule: '更明确或更新的学历覆盖旧值。',
  },
  {
    key: 'occupation',
    label: '职业',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户当前职业或行业身份。',
    extractRule: '明确提到当前职业时才提取。',
    updateRule: '新明确职业覆盖旧值。',
  },
  {
    key: 'work_schedule',
    label: '工作作息',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户长期稳定的工作节奏与作息。',
    extractRule: '只在客户明确描述长期作息时提取。',
    updateRule: '新明确描述覆盖旧值。',
  },
  {
    key: 'annual_income',
    label: '年收入',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '统一按万元/年记录的收入数字。',
    extractRule: '只接受明确数值或明确范围中值。',
    updateRule: '新明确收入覆盖旧明确收入；模糊表述不能覆盖。',
  },
  {
    key: 'net_worth_range',
    label: '净资产区间',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户明确提到的净资产量级。',
    extractRule: '只有明确说资产区间时才提取。',
    updateRule: '新明确区间覆盖旧值。',
  },
  {
    key: 'assets',
    label: '资产情况',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '房、车、股权、信托等主要资产事实。',
    extractRule: '只记录明确提到的资产事实。',
    updateRule: '新增事实可补充；明确冲突时最新覆盖。',
  },
  {
    key: 'support_budget_range',
    label: '支持预算区间',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '若涉及经济安排，可承担的支持区间。',
    extractRule: '只有客户明确谈到经济支持能力时才提取。',
    updateRule: '新明确预算覆盖旧值。',
  },
  {
    key: 'marital_history',
    label: '婚史',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户当前正式婚姻历史状态。',
    extractRule: '只接受明确表达，如未婚、离异。',
    updateRule: '新明确婚史覆盖旧值。',
  },
  {
    key: 'has_children',
    label: '是否有孩子',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'boolean',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户当前是否已有孩子。',
    extractRule: '只有明确说有或没有时才提取。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
  {
    key: 'children_notes',
    label: '孩子情况',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '孩子同住与抚养等补充说明。',
    extractRule: '只有在有孩子事实明确后才补充。',
    updateRule: '新明确说明覆盖旧说明。',
  },
  {
    key: 'primary_intent',
    label: '宏观意图',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'primary_intent',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    options: ['marriage', 'dating', 'fertility'],
    description: '客户整体目标更偏结婚、恋爱还是生育。',
    extractRule: '只有客户明确表达目标时才提取。',
    updateRule: '新的明确表达覆盖旧值。',
  },
  {
    key: 'relationship_mode',
    label: '男方关系模式',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'relationship_mode',
    matchingRole: 'hard',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    options: ['marriage_standard', 'compensated_dating', 'fertility_asset_arrangement'],
    description: '男方具体关系模式，是平台最重要的敏感筛选字段。',
    extractRule: '仅对男方提取，且必须有明确表达。',
    updateRule: '新明确模式覆盖旧模式；模糊表述进入 review。',
  },
  {
    key: 'accepts_mode_marriage_standard',
    label: '女方是否接受标准婚恋',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'pending',
    autoApply: 'review_on_conflict',
    options: ['yes', 'no', 'unknown'],
    description: '女方是否接受普通结婚导向关系。',
    extractRule: '只有女方明确表态时才能写 yes/no，否则保持 unknown。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
  {
    key: 'accepts_mode_compensated_dating',
    label: '女方是否接受恋爱且带经济安排',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'pending',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '女方是否接受带明确经济安排的恋爱关系。',
    extractRule: '只有女方明确表态时才能写 yes/no，否则保持 unknown。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖；unknown 不清空旧值。',
  },
  {
    key: 'accepts_mode_fertility_asset_arrangement',
    label: '女方是否接受生育资产安排型',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'pending',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '女方是否接受以生育与资产安排为核心的关系模式。',
    extractRule: '只有女方明确表态时才能写 yes/no，否则保持 unknown。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖；unknown 不清空旧值。',
  },
  {
    key: 'preferred_age_min',
    label: '期望最小年龄',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户希望对方的最低年龄。',
    extractRule: '只接受明确下限或区间。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'preferred_age_max',
    label: '期望最大年龄',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户希望对方的最大年龄。',
    extractRule: '只接受明确上限或区间。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'preferred_cities',
    label: '可接受城市',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string_array',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户明确能接受的对方所在城市列表。',
    extractRule: '只提取明确提到的可接受城市。',
    updateRule: '新增城市增量合并；明确排除时移除。',
  },
  {
    key: 'accepts_long_distance',
    label: '是否接受异地',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'hard',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '客户是否接受异地关系。',
    extractRule: '只有客户明确表态时才写 yes/no。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
  {
    key: 'relocation_willingness',
    label: '是否愿意迁居',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'soft',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '客户是否愿意为了关系改变常驻地。',
    extractRule: '只有客户明确表态时才写 yes/no。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
  {
    key: 'preferred_education',
    label: '可接受学历',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'education_array',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    options: ['high_school', 'associate', 'bachelor', 'master', 'phd', 'other'],
    description: '客户对对方学历的下限或可接受范围。',
    extractRule: '只接受明确要求，统一成学历枚举数组。',
    updateRule: '新明确要求覆盖旧要求。',
  },
  {
    key: 'preferred_income_min',
    label: '最低收入要求',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户对对方最低年收入的要求。',
    extractRule: '只接受明确数字或区间。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'accepts_partner_marital_history',
    label: '是否接受对方婚史',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'string_array',
    matchingRole: 'hard',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    description: '客户可接受的对方婚史范围。',
    extractRule: '只接受明确表态，如接受离异或只接受未婚。',
    updateRule: '新明确边界覆盖旧边界。',
  },
  {
    key: 'accepts_partner_children',
    label: '是否接受对方有孩子',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'hard',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '客户是否接受对方已有孩子。',
    extractRule: '只有客户明确表态时才写 yes/no。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
  {
    key: 'fertility_preference',
    label: '生育意愿',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户是否希望与对方共同生育。',
    extractRule: '只接受明确表达，如想要、可讨论、不想要。',
    updateRule: '新明确表达覆盖旧值。',
  },
  {
    key: 'dealbreakers',
    label: '绝对不能接受的条件',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string_array',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    description: '客户明确说一定不能接受的条件。',
    extractRule: '只提取绝对化表达，如一定不行、绝对不能。',
    updateRule: '新增条件增量合并；明确取消时移除。',
  },
  {
    key: 'preference_importance',
    label: '偏好重要性',
    targetTable: 'intentions',
    category: 'summary',
    valueType: 'json',
    matchingRole: 'reference',
    autoApply: 'when_high_confidence',
    description: '核心偏好字段的重要性等级映射，例如年龄=hard、城市=important。',
    extractRule: '只根据客户明确表达的语言线索提取硬性、重要、一般、无所谓。',
    updateRule: '新明确的重要性覆盖旧等级。',
  },
  {
    key: 'hobbies',
    label: '兴趣爱好',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string_array',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户长期投入时间的兴趣活动标签。',
    extractRule: '只提取明确说喜欢、常做、长期做的活动。',
    updateRule: '新增兴趣增量合并；明确不再做时移除。',
  },
  {
    key: 'exercise_habits',
    label: '运动习惯',
    targetTable: 'trait_profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户平时运动频率与态度。',
    extractRule: '只在明确描述时填写。',
    updateRule: '新明确习惯覆盖旧值。',
  },
  {
    key: 'diet_habits',
    label: '饮食习惯',
    targetTable: 'trait_profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户是否有长期稳定的饮食偏好或限制。',
    extractRule: '只在明确描述长期偏好时填写。',
    updateRule: '新明确习惯覆盖旧值。',
  },
  {
    key: 'sleep_schedule',
    label: '作息习惯',
    targetTable: 'trait_profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户长期稳定的作息特点。',
    extractRule: '只接受客户明确的长期描述。',
    updateRule: '新明确习惯覆盖旧值。',
  },
  {
    key: 'smoking_habit',
    label: '吸烟习惯',
    targetTable: 'trait_profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '当前吸烟情况，如不吸烟、偶尔吸烟、经常吸烟。',
    extractRule: '只有明确描述时填写。',
    updateRule: '新明确习惯覆盖旧值。',
  },
  {
    key: 'drinking_habit',
    label: '饮酒习惯',
    targetTable: 'trait_profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '当前饮酒情况，如不饮酒、偶尔饮酒、经常饮酒。',
    extractRule: '只有明确描述时填写。',
    updateRule: '新明确习惯覆盖旧值。',
  },
  {
    key: 'social_preference',
    label: '社交偏好',
    targetTable: 'trait_profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '更偏宅、平衡、爱社交还是高频应酬。',
    extractRule: '允许基于连续明确描述做保守总结；证据不足则不写。',
    updateRule: '更明确的新表达覆盖旧值。',
  },
  {
    key: 'spending_style',
    label: '消费方式',
    targetTable: 'trait_profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '消费观与生活方式总体倾向。',
    extractRule: '只在有明确消费观表述时填写。',
    updateRule: '更明确的新表达覆盖旧值。',
  },
  {
    key: 'communication_style',
    label: '沟通风格',
    targetTable: 'intentions',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户偏好的说话与交流方式。',
    extractRule: '允许 AI 基于客户自述做保守总结；证据不足则不写。',
    updateRule: '新更明确的标签覆盖旧值。',
  },
  {
    key: 'relationship_pace',
    label: '推进节奏',
    targetTable: 'intentions',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户希望关系发展的快慢。',
    extractRule: '只在明确表达推进偏好时填写。',
    updateRule: '新明确偏好覆盖旧值。',
  },
  {
    key: 'emotional_stability',
    label: '情绪稳定',
    targetTable: 'trait_profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    options: ['稳定', '一般', '敏感', 'unknown'],
    description: 'V1 简化版情绪稳定工作性判断。',
    extractRule: '只有客户明确描述自己的脾气和冲突反应时才填写。',
    updateRule: '新明确描述覆盖旧值；unknown 不清空旧值。',
  },
  {
    key: 'biggest_concerns',
    label: '当前最大顾虑',
    targetTable: 'intentions',
    category: 'summary',
    valueType: 'string_array',
    matchingRole: 'reference',
    autoApply: 'when_high_confidence',
    description: '客户当前最在意或最担心的匹配障碍。',
    extractRule: '只提取当前明确顾虑，最多 3 项。',
    updateRule: '新顾虑覆盖旧顾虑或增量更新。',
  },
  {
    key: 'hidden_expectations',
    label: '隐性期待',
    targetTable: 'profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'when_high_confidence',
    description: '客户没有完全直说但能保守总结出的期待。',
    extractRule: '只有证据较充分时才总结；否则不写。',
    updateRule: '最新总结可替换旧总结。',
  },
  {
    key: 'followup_strategy',
    label: '红娘跟进建议',
    targetTable: 'profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'always',
    description: 'AI 针对该客户生成的红娘推进建议。',
    extractRule: '由 AI 基于本次与历史上下文生成，不属于客户事实。',
    updateRule: '每次新音频可重算覆盖。',
  },
  {
    key: 'ai_summary',
    label: 'AI 综合描述',
    targetTable: 'profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'always',
    description: 'AI 对客户整体画像的简要总结。',
    extractRule: '由 AI 基于对话生成一句到一段总结。',
    updateRule: '最新总结覆盖旧总结。',
  },
] as const satisfies readonly FieldSpec[]

export type V1FieldSpec = (typeof V1_FIELD_SPECS)[number]
export type V1FieldKey = V1FieldSpec['key']

export const V1_FIELD_KEYS = V1_FIELD_SPECS.map((field) => field.key) as V1FieldKey[]

export const V1_FIELD_SPEC_BY_KEY = Object.fromEntries(
  V1_FIELD_SPECS.map((field) => [field.key, field])
) as Record<V1FieldKey, V1FieldSpec>

export const V1_SUMMARY_FIELD_KEYS = V1_FIELD_SPECS
  .filter((field) => field.category === 'summary')
  .map((field) => field.key) as V1FieldKey[]

export const IMPORTANCE_LEVEL_VALUES: readonly ImportanceLevel[] = [
  'hard',
  'important',
  'normal',
  'flexible',
] as const

export const TRI_STATE_VALUES: readonly TriState[] = ['yes', 'no', 'unknown']
export const PRIMARY_INTENT_VALUES: readonly PrimaryIntent[] = ['marriage', 'dating', 'fertility']
export const RELATIONSHIP_MODE_VALUES: readonly RelationshipMode[] = [
  'marriage_standard',
  'compensated_dating',
  'fertility_asset_arrangement',
]
export const EDUCATION_VALUES: readonly EducationLevel[] = [
  'high_school',
  'associate',
  'bachelor',
  'master',
  'phd',
  'other',
]

export const MACHINE_READABLE_FIELD_SPEC = V1_FIELD_SPECS.map((field) => ({
  key: field.key,
  label: field.label,
  targetTable: field.targetTable,
  category: field.category,
  valueType: field.valueType,
  matchingRole: field.matchingRole,
  autoApply: field.autoApply,
  options: ('options' in field ? field.options : undefined) ?? null,
  importanceEligible: ('importanceEligible' in field ? field.importanceEligible : undefined) ?? false,
  description: field.description,
  extractRule: field.extractRule,
  updateRule: field.updateRule,
}))
