import { EducationLevel, ImportanceLevel, PrimaryIntent, RelationshipMode, TriState } from '@/types/database'

export type FieldTargetTable = 'profiles' | 'intentions' | 'trait_profiles' | 'conversations'
export type FieldCategory = 'fact' | 'sensitive' | 'summary' | 'meta'
export type FieldValueType =
  | 'string'
  | 'number'
  | 'string_array'
  | 'education_array'
  | 'primary_intent'
  | 'relationship_mode'
  | 'tri_state'
  | 'date_time'
  | 'json'

export type FieldSpec = {
  key: string
  label: string
  targetTable: FieldTargetTable
  category: FieldCategory
  valueType: FieldValueType
  matchingRole: 'hard' | 'soft' | 'pending' | 'reference' | 'meta'
  autoApply: 'always' | 'when_high_confidence' | 'review_on_conflict'
  importanceEligible?: boolean
  options?: readonly string[]
  description: string
  extractRule: string
  updateRule: string
}

export const V1_FIELD_SPECS = [
  {
    key: 'talked_at',
    label: '谈话时间',
    targetTable: 'conversations',
    category: 'meta',
    valueType: 'date_time',
    matchingRole: 'meta',
    autoApply: 'review_on_conflict',
    description: '本次实际沟通发生时间，默认等于上传时间，只有证据明确时才修正。',
    extractRule: '只有转录稿里明确出现实际沟通时间时才输出。',
    updateRule: '明确的新时间可覆盖默认上传时间；模糊时间不要覆盖。',
  },
  {
    key: 'name',
    label: '姓名',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'review_on_conflict',
    description: '当前红娘用于识别客户的姓名或固定称呼。',
    extractRule: '只有客户身份明确且出现清晰称呼时才提取。',
    updateRule: '新明确称呼可覆盖旧值；身份冲突时进入 review。',
  },
  {
    key: 'phone',
    label: '联系方式',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'when_high_confidence',
    description: '红娘内部用于联系客户的手机号或微信。',
    extractRule: '只有客户明确提供联系方式时才提取。',
    updateRule: '新明确联系方式覆盖旧值。',
  },
  {
    key: 'nationality',
    label: '国籍',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户当前国籍。',
    extractRule: '只有客户明确说出国籍时才提取。',
    updateRule: '新明确国籍覆盖旧值。',
  },
  {
    key: 'languages',
    label: '语言',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string_array',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户长期使用或熟练使用的语言列表。',
    extractRule: '只提取客户明确说会说、常用的语言。',
    updateRule: '新增语言增量合并；明确否认时可移除。',
  },
  {
    key: 'age',
    label: '年龄',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户当前年龄，以周岁计。',
    extractRule: '只有明确说出年龄时才提取。',
    updateRule: '新的明确年龄覆盖旧年龄；模糊表达不能覆盖。',
  },
  {
    key: 'height_cm',
    label: '身高',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户当前身高，统一按厘米记录。',
    extractRule: '只有客户明确说出身高数值时才提取，例如164、一米六四、164厘米。',
    updateRule: '新的明确身高覆盖旧值；模糊表达不能覆盖。',
  },
  {
    key: 'current_city',
    label: '所在城市',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户当前主要生活或工作城市。',
    extractRule: '只提取明确主城市，口语地名要归一化。',
    updateRule: '新明确常驻城市覆盖旧值。',
  },
  {
    key: 'current_base_cities',
    label: '常驻城市',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string_array',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户长期频繁停留或往返的城市列表。',
    extractRule: '只在客户明确说经常往返/常驻时提取。',
    updateRule: '新增城市增量合并。',
  },
  {
    key: 'residency_status',
    label: '居留状态',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '户籍、签证、长期居留等状态。',
    extractRule: '只提取明确说明的居留状态。',
    updateRule: '新明确状态覆盖旧值。',
  },
  {
    key: 'travel_frequency',
    label: '流动频率',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户跨城或国际出行频率。',
    extractRule: '只提取客户明确描述的长期流动节奏。',
    updateRule: '新明确描述覆盖旧值。',
  },
  {
    key: 'education_level_v2',
    label: '学历',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    options: ['high_school_or_below', 'junior_college', 'bachelor', 'master', 'doctor', 'unknown'],
    description: '客户当前最高正式学历。',
    extractRule: '只接受明确学历表达，统一到枚举值。',
    updateRule: '更明确或更新的学历覆盖旧值。',
  },
  {
    key: 'occupation',
    label: '职业',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户当前职业或行业身份。',
    extractRule: '明确提到当前职业时才提取。',
    updateRule: '新明确职业覆盖旧值。',
  },
  {
    key: 'work_schedule',
    label: '工作作息',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户长期稳定的工作节奏与作息。',
    extractRule: '只在客户明确描述长期作息时提取。',
    updateRule: '新明确描述覆盖旧值。',
  },
  {
    key: 'monthly_income',
    label: '月收入',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '统一按万元/月记录的收入数字。若客户说年收入，换算为月收入再记录。',
    extractRule: '只接受明确数值或明确范围中值，换算为万元/月。',
    updateRule: '新明确收入覆盖旧明确收入；模糊表述不能覆盖。',
  },
  {
    key: 'net_worth_range',
    label: '净资产区间',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户明确提到的净资产量级。',
    extractRule: '只有明确说资产区间时才提取。',
    updateRule: '新明确区间覆盖旧值。',
  },
  {
    key: 'assets',
    label: '资产情况',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '房、车、股权、信托等主要资产事实。',
    extractRule: '只记录明确提到的资产事实。',
    updateRule: '新增事实可补充；明确冲突时最新覆盖。',
  },
  {
    key: 'support_budget_range',
    label: '支持预算区间',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '若涉及经济安排，可承担的支持区间。',
    extractRule: '只有客户明确谈到经济支持能力时才提取。',
    updateRule: '新明确预算覆盖旧值。',
  },
  {
    key: 'marital_history_enum',
    label: '婚史',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    options: ['never_married', 'divorced', 'widowed', 'unknown'],
    description: '客户当前正式婚姻历史状态。',
    extractRule: '只接受明确表达，如未婚→never_married、离异→divorced、丧偶→widowed。',
    updateRule: '新明确婚史覆盖旧值。',
  },
  {
    key: 'has_children_enum',
    label: '是否有孩子',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '客户当前是否已有孩子。',
    extractRule: '只有明确说有或没有时才提取：有→yes，没有→no。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
  {
    key: 'children_notes',
    label: '孩子情况',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '孩子同住与抚养等补充说明。',
    extractRule: '只有在有孩子事实明确后才补充。',
    updateRule: '新明确说明覆盖旧说明。',
  },
  {
    key: 'children_age_notes',
    label: '孩子年龄情况',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '孩子年龄段或具体年龄描述。',
    extractRule: '只有明确说出孩子年龄时才提取。',
    updateRule: '新明确说明覆盖旧说明。',
  },
  {
    key: 'birth_year_month',
    label: '出生年月',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'when_high_confidence',
    description: '客户出生年月，格式 YYYY-MM 或 YYYY 年 MM 月。',
    extractRule: '只有明确说出出生年月时才提取，格式归一化为 YYYY-MM。',
    updateRule: '新明确出生年月覆盖旧值。',
  },
  {
    key: 'bachelor_school',
    label: '本科院校',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户本科就读院校名称。',
    extractRule: '只有客户明确说出院校名称时才提取。',
    updateRule: '新明确院校覆盖旧值。',
  },
  {
    key: 'master_school',
    label: '硕士院校',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户硕士就读院校名称。',
    extractRule: '只有客户明确说出院校名称时才提取。',
    updateRule: '新明确院校覆盖旧值。',
  },
  {
    key: 'major',
    label: '专业',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户主修专业或学科方向。',
    extractRule: '只有明确说出专业名称时才提取。',
    updateRule: '新明确专业覆盖旧值。',
  },
  {
    key: 'company_name',
    label: '公司名称',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户当前就职公司名称。',
    extractRule: '只有客户明确说出公司名时才提取。',
    updateRule: '新明确公司覆盖旧值。',
  },
  {
    key: 'smokes',
    label: '是否吸烟',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '客户是否吸烟（是/否/未知）。',
    extractRule: '只有明确说明时才提取：吸烟→yes，不吸→no。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'drinks',
    label: '是否饮酒',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '客户是否饮酒（是/否/未知）。',
    extractRule: '只有明确说明时才提取：饮酒→yes，不饮→no。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'urgency_level',
    label: '成婚紧迫程度',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    options: ['low', 'normal', 'high', 'urgent', 'unknown'],
    description: '客户当前对��姻的紧迫感。',
    extractRule: '从对话情绪和时间压力判断：不急→low，正常→normal，较急→high，非常急→urgent。',
    updateRule: '新明确表达覆盖旧值。',
  },
  {
    key: 'mbti',
    label: 'MBTI',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户自述的 MBTI ���型，如 INFJ、ENFP 等。',
    extractRule: '只有客户明确说出 MBTI 类型时才提取。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'vehicle_brand',
    label: '车辆品牌',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户当前拥有的车辆品牌。',
    extractRule: '只有明确说出车辆品牌时才提取。',
    updateRule: '新明确品牌覆盖旧值。',
  },
  {
    key: 'property_notes',
    label: '房产情况',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户房产持有情况的简要说明。',
    extractRule: '只有客户明确说出房产情况时才提取。',
    updateRule: '新明确说明覆盖旧值。',
  },
  {
    key: 'primary_intent',
    label: '宏观意图',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'primary_intent',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    options: ['marriage', 'dating', 'fertility'],
    description: '客户整体目标更偏结婚、恋爱还是生育。',
    extractRule: '只有客户明确表达目标时才提取。',
    updateRule: '新的明确表达覆盖旧值。',
  },
  {
    key: 'relationship_mode',
    label: '男方关系模式',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'relationship_mode',
    matchingRole: 'hard',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    options: ['marriage_standard', 'compensated_dating', 'fertility_asset_arrangement'],
    description: '男方具体关系模式，是平台最重要的敏感筛选字段。',
    extractRule: '仅对男方提取，且必须有明确表达。',
    updateRule: '新明确模式覆盖旧模式；模糊表述进入 review。',
  },
  {
    key: 'accepts_mode_marriage_standard',
    label: '女方是否接受标准婚恋',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'pending',
    autoApply: 'review_on_conflict',
    options: ['yes', 'no', 'unknown'],
    description: '女方是否接受普通结婚导向关系。',
    extractRule: '只有女方明确表态时才能写 yes/no，否则保持 unknown。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
  {
    key: 'accepts_mode_compensated_dating',
    label: '女方是否接受恋爱且带经济安排',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'pending',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '女方是否接受带明确经济安排的恋爱关系。',
    extractRule: '只有女方明确表态时才能写 yes/no，否则保持 unknown。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖；unknown 不清空旧值。',
  },
  {
    key: 'accepts_mode_fertility_asset_arrangement',
    label: '女方是否接受生育资产安排型',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'pending',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '女方是否接受以生育与资产安排为核心的关系模式。',
    extractRule: '只有女方明确表态时才能写 yes/no，否则保持 unknown。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖；unknown 不清空旧值。',
  },
  {
    key: 'preferred_age_min',
    label: '期望最小年龄',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户希望对方的最低年龄。',
    extractRule: '只接受明确下限或区间。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'preferred_age_max',
    label: '期望最大年龄',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户希望对方的最大年龄。',
    extractRule: '只接受明确上限或区间。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'preferred_cities',
    label: '可接受城市',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string_array',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户明确能接受的对方所在城市列表。',
    extractRule: '只提取明确提到的可接受城市。',
    updateRule: '新增城市增量合并；明确排除时移除。',
  },
  {
    key: 'accepts_long_distance',
    label: '是否接受异地',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'hard',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '客户是否接受异地关系。',
    extractRule: '只有客户明确表态时才写 yes/no。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
  {
    key: 'relocation_willingness',
    label: '是否愿意迁居',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'soft',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '客户是否愿意为了关系改变常驻地。',
    extractRule: '只有客户明确表态时才写 yes/no。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
  {
    key: 'preferred_education',
    label: '可接受学历',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'education_array',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    options: ['high_school', 'associate', 'bachelor', 'master', 'phd', 'other'],
    description: '客户对对方学历的下限或可接受范围。',
    extractRule: '只接受明确要求，统一成学历枚举数组。',
    updateRule: '新明确要求覆盖旧要求。',
  },
  {
    key: 'preferred_income_min',
    label: '最低收入要求',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户对对方最低年收入的要求。',
    extractRule: '只接受明确数字或区间。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'accepts_partner_marital_history',
    label: '是否接受对方婚史',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'string_array',
    matchingRole: 'hard',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    description: '客户可接受的对方婚史范围。',
    extractRule: '只接受明确表态，如接受离异或只接受未婚。',
    updateRule: '新明确边界覆盖旧边界。',
  },
  {
    key: 'accepts_partner_children',
    label: '是否接受对方有孩子',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'hard',
    autoApply: 'review_on_conflict',
    importanceEligible: true,
    options: ['yes', 'no', 'unknown'],
    description: '客户是否接受对方已有孩子。',
    extractRule: '只有客户明确表态时才写 yes/no。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
  {
    key: 'fertility_preference',
    label: '生育意愿',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户是否希望与对方共同生育。',
    extractRule: '只接受明确表达，如想要、可讨论、不想要。',
    updateRule: '新明确表达覆盖旧值。',
  },
  {
    key: 'dealbreakers',
    label: '绝对不能接受的条件',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string_array',
    matchingRole: 'hard',
    autoApply: 'when_high_confidence',
    description: '客户明确说一定不能接受的条件。',
    extractRule: '只提取绝对化表达，如一定不行、绝对不能。',
    updateRule: '新增条件增量合并；明确取消时移除。',
  },
  {
    key: 'preference_importance',
    label: '偏好重要性',
    targetTable: 'intentions',
    category: 'summary',
    valueType: 'json',
    matchingRole: 'reference',
    autoApply: 'when_high_confidence',
    description: '核心偏好字段的重要性等级映射，例如年龄=hard、城市=important。',
    extractRule: '只根据客户明确表达的语言线索提取硬性、重要、一般、无所谓。',
    updateRule: '新明确的重要性覆盖旧等级。',
  },
  {
    key: 'hobbies',
    label: '兴趣爱好',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string_array',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户长期投入时间的兴趣活动标签。',
    extractRule: '只提取明确说喜欢、常做、长期做的活动。',
    updateRule: '新增兴趣增量合并；明确不再做时移除。',
  },
  {
    key: 'exercise_habits',
    label: '运动习惯',
    targetTable: 'trait_profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户平时运动频率与态度。',
    extractRule: '只在明确描述时填写。',
    updateRule: '新明确习惯覆盖旧值。',
  },
  {
    key: 'diet_habits',
    label: '饮食习惯',
    targetTable: 'trait_profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户是否有长期稳定的饮食偏好或限制。',
    extractRule: '只在明确描述长期偏好时填写。',
    updateRule: '新明确习惯覆盖旧值。',
  },
  {
    key: 'sleep_schedule',
    label: '作息习惯',
    targetTable: 'trait_profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户长期稳定的作息特点。',
    extractRule: '只接受客户明确的长期描述。',
    updateRule: '新明确习惯覆盖旧值。',
  },
  {
    key: 'smoking_habit',
    label: '吸烟习惯',
    targetTable: 'trait_profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '当前吸烟情况，如不吸烟、偶尔吸烟、经常吸烟。',
    extractRule: '只有明确描述时填写。',
    updateRule: '新明确习惯覆盖旧值。',
  },
  {
    key: 'drinking_habit',
    label: '饮酒习惯',
    targetTable: 'trait_profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '当前饮酒情况，如不饮酒、偶尔饮酒、经常饮酒。',
    extractRule: '只有明确描述时填写。',
    updateRule: '新明确习惯覆盖旧值。',
  },
  {
    key: 'social_preference',
    label: '社交偏好',
    targetTable: 'trait_profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '更偏宅、平衡、爱社交还是高频应酬。',
    extractRule: '允许基于连续明确描述做保守总结；证据不足则不写。',
    updateRule: '更明确的新表达覆盖旧值。',
  },
  {
    key: 'spending_style',
    label: '消费方式',
    targetTable: 'trait_profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '消费观与生活方式总体倾向。',
    extractRule: '只在有明确消费观表述时填写。',
    updateRule: '更明确的新表达覆盖旧值。',
  },
  {
    key: 'communication_style',
    label: '沟通风格',
    targetTable: 'intentions',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户偏好的说话与交流方式。',
    extractRule: '允许 AI 基于客户自述做保守总结；证据不足则不写。',
    updateRule: '新更明确的标签覆盖旧值。',
  },
  {
    key: 'relationship_pace',
    label: '推进节奏',
    targetTable: 'intentions',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户希望关系发展的快慢。',
    extractRule: '只在明确表达推进偏好时填写。',
    updateRule: '新明确偏好覆盖旧值。',
  },
  {
    key: 'emotional_stability',
    label: '情绪稳定',
    targetTable: 'trait_profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    options: ['稳定', '一般', '敏感', 'unknown'],
    description: 'V1 简化版情绪稳定工作性判断。',
    extractRule: '只有客户明确描述自己的脾气和冲突反应时才填写。',
    updateRule: '新明确描述覆盖旧值；unknown 不清空旧值。',
  },
  {
    key: 'biggest_concerns',
    label: '当前最大顾虑',
    targetTable: 'intentions',
    category: 'summary',
    valueType: 'string_array',
    matchingRole: 'reference',
    autoApply: 'when_high_confidence',
    description: '客户当前最在意或最担心的匹配障碍。',
    extractRule: '只提取当前明确顾虑，最多 3 项。',
    updateRule: '新顾虑覆盖旧顾虑或增量更新。',
  },
  {
    key: 'hidden_expectations',
    label: '隐性期待',
    targetTable: 'profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'when_high_confidence',
    description: '客户没有完全直说但能保守总结出的期待。',
    extractRule: '只有证据较充分时才总结；否则不写。',
    updateRule: '最新总结可替换旧总结。',
  },
  {
    key: 'followup_strategy',
    label: '红娘跟进建议',
    targetTable: 'profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'always',
    description: 'AI 针对该客户生成的红娘推进建议。',
    extractRule: '由 AI 基于本次与历史上下文生成，不属于客户事实。',
    updateRule: '每次新音频可重算覆盖。',
  },
  {
    key: 'ai_summary',
    label: 'AI 综合描述',
    targetTable: 'profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'always',
    description: 'AI 对客户整体画像的简要总结。',
    extractRule: '由 AI 基于对话生成一句到一段总结。',
    updateRule: '最新总结覆盖旧总结。',
  },

  // ── Phase-1 新增字段 ──────────────────────────────────────────────

  // profiles — 身份 / 联系
  {
    key: 'wechat_id',
    label: '微信号',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'when_high_confidence',
    description: '客户微信 ID，用于联系或核查身份。',
    extractRule: '只有客户明确说出微信号时才提取。',
    updateRule: '新明确微信号覆盖旧值。',
  },
  {
    key: 'weight_kg',
    label: '体重',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户当前体重，统一按公斤记录。',
    extractRule: '只有明确说出体重数值时才提取，例如 50kg、一百斤（换算为 50）。',
    updateRule: '新的明确体重覆盖旧值。',
  },
  {
    key: 'doctor_school',
    label: '博士院校',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户博士就读院校名称。',
    extractRule: '只有客户明确说出博士院校名称时才提取。',
    updateRule: '新明确院校覆盖旧值。',
  },
  {
    key: 'hukou_city',
    label: '户籍城市',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户户口所在城市。',
    extractRule: '只有明确提到户籍所在地时才提取。',
    updateRule: '新明确户籍城市覆盖旧值。',
  },
  {
    key: 'native_place',
    label: '祖籍',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户原籍或老家所在地。',
    extractRule: '只有明确提到老家/祖籍时才提取。',
    updateRule: '新明确值覆盖旧值。',
  },

  // profiles — 收入 / 资产
  {
    key: 'income_source_type',
    label: '收入来源',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    options: ['salary', 'dividend', 'self_business', 'mixed', 'other', 'unknown'],
    description: '客户主要收入来源性质。',
    extractRule: '工资→salary，分红/投资→dividend，自营→self_business，多种→mixed。只有明确表述时才提取。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'has_property',
    label: '是否有房',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    options: ['yes', 'no', 'unknown'],
    description: '客户是否持有不动产。',
    extractRule: '有房→yes，没有→no；只有明确说时才提取。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
  {
    key: 'property_count',
    label: '房产套数',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户持有的不动产套数。',
    extractRule: '只有明确说出套数时才提取。',
    updateRule: '新明确数值覆盖旧值。',
  },
  {
    key: 'has_vehicle',
    label: '是否有车',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    options: ['yes', 'no', 'unknown'],
    description: '客户是否持有私家车。',
    extractRule: '有车→yes，没有→no；只有明确说时才提取。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
  {
    key: 'vehicle_model',
    label: '车辆型号',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户车辆的具体型号，如 Model 3、宝马 3 系。',
    extractRule: '只有明确说出型号时才提取。',
    updateRule: '新明确型号覆盖旧值。',
  },
  {
    key: 'family_asset_band',
    label: '家庭总资产',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    options: ['A7', 'A8', 'A9', 'A10'],
    description: '家庭总资产等级：A7=百万级，A8=千万级，A9=亿级，A10=十亿以上。',
    extractRule: '只接受明确数量级描述，映射到最接近的等级。',
    updateRule: '新明确等级覆盖旧值。',
  },
  {
    key: 'financial_assets_notes',
    label: '金融资产说明',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '股票、基金、信托等金融资产的补充说明。',
    extractRule: '只有客户明确提到金融资产细节时才提取。',
    updateRule: '新明确说明覆盖旧值。',
  },

  // profiles — 婚育情况
  {
    key: 'marital_history_notes',
    label: '婚史补充说明',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '婚史的补充说明，如离婚原因、时间等。',
    extractRule: '只有客户明确提到婚史细节时才提取。',
    updateRule: '新明确说明覆盖旧值。',
  },
  {
    key: 'children_count',
    label: '孩子数量',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户当前已有孩子的数量。',
    extractRule: '只有明确说出孩子数量时才提取。',
    updateRule: '新明确数值覆盖旧值。',
  },
  {
    key: 'custody_status',
    label: '孩子抚养权',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    options: ['self', 'ex_partner', 'shared', 'other', 'unknown'],
    description: '客户孩子的抚养权归属情况。',
    extractRule: '只有明确说明时才提取。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'financial_ties_with_ex_partner',
    label: '与前任是否有金融往来',
    targetTable: 'profiles',
    category: 'sensitive',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'review_on_conflict',
    options: ['yes', 'no', 'unknown'],
    description: '客户与前任之间是否仍存在抚养费、共同房贷等金融关系。',
    extractRule: '只有客户明确提到与前任有/无经济往来时才提取。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },

  // profiles — 生活习惯频率
  {
    key: 'smoking_frequency',
    label: '吸烟频率',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    options: ['occasionally', 'frequently', 'daily', 'unknown'],
    description: '客户吸烟的频率，在已确认吸烟（smokes=yes）时才有意义。',
    extractRule: '只有在 smokes=yes 且客户明确描述频率时才提取。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'drinking_frequency',
    label: '饮酒频率',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    options: ['occasionally', 'frequently', 'daily', 'unknown'],
    description: '客户饮酒的频率，在已确认饮酒（drinks=yes）时才有意义。',
    extractRule: '只有在 drinks=yes 且客户明确描述频率时才提取。',
    updateRule: '新明确值覆盖旧值。',
  },

  // profiles — 家庭背景
  {
    key: 'siblings_summary',
    label: '兄弟姐妹情况',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户兄弟姐妹人数与基本情况。',
    extractRule: '只有明确提到兄弟姐妹时才提取。',
    updateRule: '新明确说明覆盖旧值。',
  },
  {
    key: 'parents_occupation',
    label: '父母职业',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户父母当前或退休前的职业情况。',
    extractRule: '只有明确提到父母职业时才提取。',
    updateRule: '新明确说明覆盖旧值。',
  },
  {
    key: 'parents_marital_status',
    label: '父母婚姻状况',
    targetTable: 'profiles',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    options: ['together', 'divorced', 'widowed', 'unknown'],
    description: '客户父母当前婚姻状态。',
    extractRule: '只有明确提到父母婚姻状况时才提取。',
    updateRule: '新明确值覆盖旧值。',
  },

  // profiles — 自我描述
  {
    key: 'personality_summary',
    label: '性格描述',
    targetTable: 'profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户自述或 AI 总结的性格特征。',
    extractRule: '允许基于明确自述做保守总结；证据不足则不写。',
    updateRule: '新更明确的描述覆盖旧值。',
  },
  {
    key: 'self_description',
    label: '自我描述',
    targetTable: 'profiles',
    category: 'summary',
    valueType: 'string',
    matchingRole: 'reference',
    autoApply: 'when_high_confidence',
    description: '客户自己说的自我介绍或自我评价原文。',
    extractRule: '只有客户明确进行自我介绍时才提取，尽量保留原话。',
    updateRule: '新的自述覆盖旧值。',
  },

  // intentions — 生育专属
  {
    key: 'fertility_timeline',
    label: '生育时间规划',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户希望在多长时间内完成生育。',
    extractRule: '只有明确说出生育时间预期时才提取，如"2年内""越快越好"。',
    updateRule: '新明确表达覆盖旧值。',
  },
  {
    key: 'desired_children_count',
    label: '期望生育数量',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户希望生育的孩子数量。',
    extractRule: '只有明确说出期望孩子数量时才提取。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'biological_child_requirement',
    label: '是否要求对方有生育能力',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'review_on_conflict',
    options: ['true', 'false'],
    description: '客户是否明确要求对方具备生育能力。',
    extractRule: '只有客户明确提出此要求时才提取。',
    updateRule: '新明确表态覆盖旧值。',
  },
  {
    key: 'co_parenting_expectation',
    label: '育儿分工期望',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户对育儿分工的期望，如双方共同承担、主要由女方负责等。',
    extractRule: '只有明确描述分工期望时才提取。',
    updateRule: '新明确描述覆盖旧值。',
  },

  // intentions — 结婚专属
  {
    key: 'wedding_scale_preference',
    label: '婚礼规模偏好',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户对婚礼规模的期望，如小型婚礼、传统大婚、不在意。',
    extractRule: '只有明确描述婚礼规模偏好时才提取。',
    updateRule: '新明确描述覆盖旧值。',
  },
  {
    key: 'financial_arrangement_expectation',
    label: '财务安排期望',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户对婚后或关系中财务安排的期望，如 AA 制、男方主导、婚前公证。',
    extractRule: '只有明确描述财务安排期望时才提取。',
    updateRule: '新明确描述覆盖旧值。',
  },
  {
    key: 'accepts_parents_cohabitation',
    label: '是否接受父母同住',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户是否接受与父母同住或父母住在附近。',
    extractRule: '只有明确表态时才提取，如接受/不接受/视情况。',
    updateRule: '新明确描述覆盖旧值。',
  },
  {
    key: 'settle_city_preferences',
    label: '未来定居城市偏好',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string_array',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户婚后希望定居的城市列表。',
    extractRule: '只有明确提到婚后定居城市时才提取。',
    updateRule: '新增城市增量合并；明确排除时移除。',
  },

  // intentions — 恋爱专属
  {
    key: 'dating_frequency_expectation',
    label: '约会频率期望',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户希望的约会频率，如每周见面、每月两次。',
    extractRule: '只有明确描述约会频率期望时才提取。',
    updateRule: '新明确描述覆盖旧值。',
  },
  {
    key: 'monthly_date_budget',
    label: '付出意愿 / 月约会预算',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户愿意在约会上投入的月度预算或付出意愿描述。',
    extractRule: '只有明确提到约会预算或付出意愿时才提取。',
    updateRule: '新明确描述覆盖旧值。',
  },

  // intentions — 通用补充
  {
    key: 'preferred_height_min',
    label: '期望对方最低身高',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'number',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户对对方身高的最低要求，统一按厘米记录。',
    extractRule: '只接受明确的身高下限数值。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'preferred_net_worth_min',
    label: '期望对方最低净资产',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    importanceEligible: true,
    description: '客户对对方净资产的下限要求，可为文字描述。',
    extractRule: '只接受明确的资产下限表达。',
    updateRule: '新明确值覆盖旧值。',
  },
  {
    key: 'preferred_industry_tags',
    label: '期望对方行业',
    targetTable: 'intentions',
    category: 'fact',
    valueType: 'string_array',
    matchingRole: 'soft',
    autoApply: 'when_high_confidence',
    description: '客户希望对方从事的行业列表。',
    extractRule: '只有明确提到期望行业时才提取。',
    updateRule: '新增行业增量合并；明确排除时移除。',
  },
  {
    key: 'prenup_acceptance',
    label: '婚前协议接受度',
    targetTable: 'intentions',
    category: 'sensitive',
    valueType: 'tri_state',
    matchingRole: 'soft',
    autoApply: 'review_on_conflict',
    options: ['yes', 'no', 'unknown'],
    description: '客户是否接受签署婚前财产协议。',
    extractRule: '只有客户明确表态时才写 yes/no。',
    updateRule: 'yes/no 只允许被新的明确 yes/no 覆盖。',
  },
] as const satisfies readonly FieldSpec[]

export type V1FieldSpec = (typeof V1_FIELD_SPECS)[number]
export type V1FieldKey = V1FieldSpec['key']

export const V1_FIELD_KEYS = V1_FIELD_SPECS.map((field) => field.key) as V1FieldKey[]

export const V1_FIELD_SPEC_BY_KEY = Object.fromEntries(
  V1_FIELD_SPECS.map((field) => [field.key, field])
) as Record<V1FieldKey, V1FieldSpec>

export const V1_SUMMARY_FIELD_KEYS = V1_FIELD_SPECS
  .filter((field) => field.category === 'summary')
  .map((field) => field.key) as V1FieldKey[]

export const IMPORTANCE_LEVEL_VALUES: readonly ImportanceLevel[] = [
  'hard',
  'important',
  'normal',
  'flexible',
] as const

export const TRI_STATE_VALUES: readonly TriState[] = ['yes', 'no', 'unknown']
export const PRIMARY_INTENT_VALUES: readonly PrimaryIntent[] = ['marriage', 'dating', 'fertility']
export const RELATIONSHIP_MODE_VALUES: readonly RelationshipMode[] = [
  'marriage_standard',
  'compensated_dating',
  'fertility_asset_arrangement',
]
export const EDUCATION_VALUES: readonly EducationLevel[] = [
  'high_school',
  'associate',
  'bachelor',
  'master',
  'phd',
  'other',
]

export const MACHINE_READABLE_FIELD_SPEC = V1_FIELD_SPECS.map((field) => ({
  key: field.key,
  label: field.label,
  targetTable: field.targetTable,
  category: field.category,
  valueType: field.valueType,
  matchingRole: field.matchingRole,
  autoApply: field.autoApply,
  options: ('options' in field ? field.options : undefined) ?? null,
  importanceEligible: ('importanceEligible' in field ? field.importanceEligible : undefined) ?? false,
  description: field.description,
  extractRule: field.extractRule,
  updateRule: field.updateRule,
}))
